///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// This file is auto-generated by api_gen. DO NOT EDIT!
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#pragma once

#include <stdbool.h>
#include <stdint.h>
#include <string.h>
#include "manual.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct FlApplicationSettings {
<<<<<<< HEAD

  uint32_t width;

  uint32_t height;
=======
    uint32_t some_data;
>>>>>>> main
} FlApplicationSettings;

#include "application_settings.inl"
#ifdef __cplusplus
}
#endif
