///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// This file is auto-generated by api_gen. DO NOT EDIT!
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#pragma once

#include "manual.h"
#include <stdbool.h>
#include <stdint.h>
#include <string.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum FlSvgFlags {
  // Render the SVG image using RGBA format
  FlSvgFlags_Rgba = 0,
  // Render the SVG image using Alpha only
  FlSvgFlags_Alpha = 1,
} FlSvgFlags;

typedef uint64_t FlImage;

typedef struct FlImageInfo {
  // width of the image
  uint32_t width;
  // height of the Image
  uint32_t height;
} FlImageInfo;

#include "image.inl"
#ifdef __cplusplus
}
#endif
