///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// This file is auto-generated by api_gen. DO NOT EDIT!
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#pragma once

#include <stdbool.h>
#include <stdint.h>
#include <string.h>
#include "image.h"
#include "manual.h"
#include "shader.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct FlIo {
} FlIo;

// Load image from file/url. Supported formats are: JPG, PNG, WEBP
static void fl_io_dummy();

#include "io.inl"
#ifdef __cplusplus
}
#endif
