///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// This file is auto-generated by api_gen. DO NOT EDIT!
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#pragma once

#include "manual.h"
#include <stdbool.h>
#include <stdint.h>
#include <string.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct FlRect {
  int x;
  int y;
  int width;
  int height;
} FlRect;

typedef struct FlVec2 {
  float x;
  float y;
} FlVec2;

typedef struct FlIVec2 {
  int x;
  int y;
} FlIVec2;

#ifdef __cplusplus
}
#endif
