///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// This file is auto-generated by api_gen. DO NOT EDIT!
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#pragma once

#include "manual.h"
#include <stdbool.h>
#include <stdint.h>
#include <string.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct FlRect {
  i32 x;
  i32 y;
  i32 width;
  i32 height;
} FlRect;

typedef struct FlVec2 {
  f32 x;
  f32 y;
} FlVec2;

typedef struct FlIVec2 {
  i32 x;
  i32 y;
} FlIVec2;

#ifdef __cplusplus
}
#endif
