///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// This file is auto-generated by api_gen. DO NOT EDIT!
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#pragma once

#include "manual.h"
#include <stdbool.h>
#include <stdint.h>
#include <string.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct FlRect {

  int x;

  int y;

  int width;

  int height;
} FlRect;

typedef struct FlVec2 {
  // x position
  float x;
  // y position
  float y;
} FlVec2;

typedef struct FlIVec2 {
  // x position
  int x;
  // y position
  int y;
} FlIVec2;

#include "math_data.inl"
#ifdef __cplusplus
}
#endif
