///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// This file is auto-generated by api_gen. DO NOT EDIT!
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#pragma once

#include "manual.h"
#include <stdbool.h>
#include <stdint.h>
#include <string.h>

#ifdef __cplusplus
extern "C" {
#endif

// Texture format specificed when using [CreateTexture] command
typedef enum FlTextureFormat {
  // Single byte texture in linear format
  FlTextureFormat_R8Linear = 0,
  // 3 byte R,G,B format (sRGB)
  FlTextureFormat_Rgb8Srgb = 1,
  // 3 byte R,G,B format (LINEAR)
  FlTextureFormat_Rgb8Linear = 2,
  // 4 byte R,G,B,A format (sRGB)
  FlTextureFormat_Rgba8Srgb = 3,
  // 4 byte R,G,B,A format (LINEAR)
  FlTextureFormat_Rgba8Linear = 4,
  // 16-bit single format. This will mostly be used for temporary things such as
  // blurs that requires more// than one pass rendering. i16 or f16 will allow
  // better accuracy, but R8_LINEAR can be used in worst case// in case the
  // rendering backend doesn't support this format
  FlTextureFormat_I16OrF16Linear = 5,
} FlTextureFormat;

#ifdef __cplusplus
}
#endif
